### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by romellem** [romellem/christmas-setlists#1]
```css
:root {
        --color-primary: hsl(120, 50%, 90%);
        --color-secondary: hsl(120, 50%, 10%);
        --color-tertiary: hsl(180, 80%, 20%);
        --color-accent: hsl(60, 80%, 20%);
    }
.dark {
        --color-primary: hsl(120, 50%, 10%);
        --color-secondary: hsl(120, 50%, 90%);
        --color-tertiary: hsl(180, 80%, 80%);
        --color-accent: hsl(60, 80%, 80%);
    }
```

From https://www.iamsajid.com/colors/ ([source code][1]), hue 120 as base.

[1]: https://romellem.github.io/paste/#XQAAAQDyHwAAAAAAAAA9iImGVD/UQZfk9s7gJ6IZH736V079wXIAs8T1sN0rXED8f6qXD+wfcNS5F+mheFwFHBPknO7N4766Ddu3CS8dGjrJCkYuumoaNvT0tJUOfbHJk7rfASaMTkV5mTVKwkQ5mtMISj5s6Rn6K30vg79f8Ah8CIZPn7+ehSGXrI/9SE2T0Qnrhy6vu9p1S3cIvLBva2rM+6u/VfPqR9ZUDTNB82XxAeVTZ5UxBqGPL/i3CkkyBx5dgQOI5mlN1/G+nW8iXXRUnypvTGfquPp/8sO0dUNvDsusaU95lyuWIi5OYzdiUwu3yZS+lVJ7bPSxUdXoadq0GUNbGNKJgA+avx77fWhcFvHtkTPunBrWxZIVyXioYgrknC6gSaPp+N524aleVf5baGhef3lCoDR48HN8KeUMPxSC3CsIfCeW9v/jpl5flcWeoVP46a4RTI/2lBjiNE4E24hiknQv3UX6idkDzeQ9P/2gw1iZKo2aVyiXNlXTLItHKcSGWnBZ5Syd3umnvLHoaDyFyPaJFJfsVhQWhR4mSrJ1ZGbJgfD0x9BTc+nUKpd3pYLcHktEStF1JSyBvpuJQNlfsCoFnQYCp9iHIGKoizkT/w/q34DqDV8oSA1qc74GrC1/lnGi/jEmiczqjmDvhiacE79pvB68V+tM0eDU95nAlsRecKBuawTVdkkGq74KTyW//eJFh4D8Bs9/6qt/XUM+Wi7vxy6vS+3E+4QKMy274aU0paNHsyWhvHkaL17/CEbUutx2EFWkk7KftS2PiJVw2dqGBRyTzTRgXXBxrs19HIjecqtpQsLYRRRiJEHY7sQ216OLSTDr6zt3fnQBSRgFGwRIaHHHkF7nLFGBsCpRY5F3lppdV7QFTxfdxVvREPnL24TBWfuGkro2GcmDm2bH2KAelOc3biObBWsDkwsJrGfasdYvHEzJHSyMxxbeAMo+StObtKHOTK8H77FXyuWFUv7n9wTgnnOstsAZymFKjqHkY0G68CyAkEPZGmmRxtznbwRG+qpyLv5GOEBkSLRo1D6BT449WPSUiSLElDE4lzeUCrIAnqCTOcmdORLiCB5bQwbGTE53Tp3bECllXdf7E2YCYJ0LKR89W1emDJ5+tAMZmqk/4aoshm1P6PRxJc0lwWGBawcYEgZkbCytka8wktyrTRb87fG0tY8JzEay84k43yL30otUpydhH2wB5yvPWccXuhk8MJ5mVIya2gtLfynA6QfzaYkjm9Yan8YRkFpVj1XuLnTfgyJUMzDmcVU37MYiEw7mFZvZYBiDBZcs0OBxr5popXTRtgYS1P0zzNlohoy8R2qtwzgONjy+lBf0pfLLMcWIxXOglL0YbIrZ5TdlQv+3xCclQt2mschBYdBWqR9/zWjStm+vf2xrBwsly0F+G135HV+0sZ+dOzMgkKGQ/eyiH7QksMNJ5Y2yPIskIo7x9MPWn8LZDY/EpmRz6/hoGg3oNF+X5xEIueHIZOSwsvPaEwodxLinFheymj5j8QftSaDHjgo0oR3AWwsdrfWhQTWPbuxumtJjQNP/AHZ9e/DGXfGJiPGuf906WfcoNvbyofi4dUn70lQCyaSIlSOjhYm0wcO27LarbK2RJADq8bN5dkhb761dAnNLE31ARj7hc2DJe54u9l6pK+6JsGhJlAjVd7TblfQhRTMM2X6zIXXnPSAUWg/hnVR4SdsuTp9vIFz9x4WUq7jam49q05EnVXrEFvyFNoFb1GI6dfbqE2UV2ihx/top//LgkDL+BF9PdRizBP8dLLCWr6kCFGEMUdnhyfF+xga726KBLfCpjye7Gv0Rx9jiMXVney0/Q8pHcMJKUsMGvlsKIok5GRfPuabUT+Pt0ljIlIU9VgIL/SmfDgXL+ImwMmNaLibH9PoJRhRqjqLTn38VHhwVPcrzoZSDRmTxF6ru77KBgnYFIoOjyo+Bu6zml0A+FSQ5heRAgc6bkd/RLaF+5QA9RtdE2vh67hkt0Pnc30fL24R1lG66XVIqd/BGMNjLwwPhWwRPpU3BDqDlXB7cIOk1nELpNBrbRA5hg/TWUEFUF+KVJDHztqX58ckC3xmERHLnWy+OhHplCz8sBLyVEXdWCvqUumwKfGxdRiyPdB955ddrj4NvjcXfSUCDfO3fVvvVjSb2D2OdTfjJa6ZFK7Sfvc9Wr5yq9ZJRiJH4EzbUCJww5k+Of3jfnswfLdhYGcMZ/PlbXoLOtvs4Rs13ZukUjSFGqlDSbiQjh0Uipv1q752kSmVaDp5/zpFJd9cB7aB7RgoG5gPil3N3odY2JT0ZW/axzmhG2RRYsQhEMGvql1nYoJ/GQLc4gH0J1iAQRbzg6q+QHHZ17QFPueNH+pJGrbd8os8d1ojpZyAosk0O+0HRZ2rDXrmx1Z44UF25LM0+IBDuHeQEVY0q/L+eVooDCijnMByYekPIrjvcInY4Yrv5VU0M4kOCo4MF6KdNQ2gYHes0jyS1fP/DVirk1EnXvwv/0WRf3Po9BWC16myHkCjdr1Tx4lUxfMX3KH6RFfQs1ktZg0S/Z+a02gfFlwUVyS+HjSvba1o/ZfBhc3U0iDM9z7VPsfxPRkUegbvZkvn1bYiQCbvPiDWZh4UhvINh5A/wVXLSbWEJVrsUqC1eVGc3uKCLJ4qxwSeSBfdlraR+M6XguBbdkbbhxoz0nZV2BzLdEs+jyyVtppXOu69zSPQbD8cdunjY6u9ebTiFSPd2VKsbkKvunnP+DOB3vdlHNjyDjNRIDHEMw5ioklIWTueOiPAZN6yqJMkU0q86S2y/Bkdztt/I3Fm/XgVPaOMg7fIHgeDJPvmF4Ms18IZ9wfpBOHQF8u/IS3s6rleo/EurJxOZ3GH5A8snCMVMbe/Fm++wfNkY2zSAWfPjkft9Y48xdkNPOkxhq/ACy3fH/MmV+DRjKd+QK/F2p8Z6OHyN9HLN+pqHny7d058yuLac40VKf1l3ZktAriIrfq3pYhFzGsfh4Mrxfb1JTAaEg0p4yfZsKARRN7itt+9bOyZBbCgXPDloV5lmfzlP78yvtTn1kEhnWn92ths9I3FlGrBAElDyTSKG5KONhtq+gyXifk0n56qlvnOu7jPnJD7yyCKX3BfwGWj78OHZdpUv2gpGzk6SeiFxDd4bXYFF+3kambFZZSACboefEq3U6omGxx/lI/Kn5TZHqfs97R1EvBzAROwWN4gF2MJedI9ERxV46P77zNj+
